export const ErrorCode = {
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_INPUT: "INVALID_INPUT",
  NOT_FOUND: "NOT_FOUND",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  PATH_OUTSIDE_SANDBOX: "PATH_OUTSIDE_SANDBOX",
  PATH_BLOCKED: "PATH_BLOCKED",
  EXTENSION_NOT_ALLOWED: "EXTENSION_NOT_ALLOWED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  COMMAND_NOT_ALLOWED: "COMMAND_NOT_ALLOWED",
  RESOURCE_FAILED_TO_START: "RESOURCE_FAILED_TO_START",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
  PLAYER_NOT_OPTED_IN: "PLAYER_NOT_OPTED_IN",
  SUBJECT_LIMIT_REACHED: "SUBJECT_LIMIT_REACHED",
  CLIENT_PROBE_TIMEOUT: "CLIENT_PROBE_TIMEOUT",
  BODY_TOO_LARGE: "BODY_TOO_LARGE",
  RATE_LIMITED: "RATE_LIMITED",
  TIMEOUT: "TIMEOUT",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export type AppError = {
  code: ErrorCodeType;
  message: string;
  details?: Record<string, unknown>;
};

export const HTTP_STATUS: Record<ErrorCodeType, number> = {
  UNAUTHORIZED: 401,
  INVALID_INPUT: 400,
  NOT_FOUND: 404,
  TOOL_NOT_FOUND: 404,
  RESOURCE_NOT_FOUND: 404,
  PATH_OUTSIDE_SANDBOX: 403,
  PATH_BLOCKED: 403,
  EXTENSION_NOT_ALLOWED: 403,
  FILE_TOO_LARGE: 413,
  COMMAND_NOT_ALLOWED: 403,
  RESOURCE_FAILED_TO_START: 500,
  PLAYER_NOT_FOUND: 404,
  PLAYER_NOT_OPTED_IN: 403,
  SUBJECT_LIMIT_REACHED: 429,
  CLIENT_PROBE_TIMEOUT: 504,
  BODY_TOO_LARGE: 413,
  RATE_LIMITED: 429,
  TIMEOUT: 504,
  INTERNAL: 500,
};
